### PR TITLE
fix: scaleFactor not being used for mousewheel

### PR DESCRIPTION
**Pull request by auroranil**
Resolves issue #62 

Also add `scaleFactor` prop to Viewer storybook, to see if it is working or not.

### CODE REVIEW

**Comment by chrvadala** [comment]
Thanks for your PR. I will check it next Monday

**Comment by auroranil** [comment]
Also resolves #66, by adding prop `SVGStyle` that allows clients to change style of rect canvas, such as adding stroke or adding some shadow effect. Prop `SVGBackground` is left alone for backwards compatibility reasons.

**Comment by chrvadala** [comment]
In the end, I preferred to introduce scaleFactorOnWheel, because with numbers greater then 1.7 the wheel doesn't work very well (especially on macos)

**Comment by auroranil** [comment]
Yeah that's fine with me. I'll use the prop `scaleFactorOnWheel` instead.

**Comment by chrvadala** [comment]
Released with v2.14

**Pull request merged**
