### PR TITLE
Compare to SVGHeight instead of prevSVGHeight

### PR DESCRIPTION
**Pull request by jakoblaegdsmand**
Fixes a bug that causes the viewer not to update when changing height of the embedded SVG.

### CODE REVIEW

**Comment by jakoblaegdsmand** [comment]
I was going to write up an issue about this, but then i discovered where the problem should be fixed, so I decided to make a PR instead. 

Thanks for a great framework!

**Comment by chrvadala** [comment]
Great! Thanks for this PR. I'm going to release a new version

**Comment by chrvadala** [comment]
Fixed with 3.0.2. You're now in the contributors list

**Comment by jakoblaegdsmand** [comment]
Thanks! Glad to help

**Pull request merged**
